const STORAGE_KEY="heartbox.entries.v1";
const BEAT_COUNT_KEY="heartbox.beatCount.v1";
const LAST_HUG_KEY="heartbox.lastHug.v1";
const LAST_MOOD_KEY="heartbox.lastMood.v1";
const LAST_MOON_KEY="heartbox.lastMoon.v1";
const dailyLines=["你一转念，心光之地就亮一下。","今天也可以慢慢来，月亮会等你。","把耳朵贴过来：咚。咚。咚。","小小的光，也能陪人走很远。","没理由也可以扑进怀里。","今天不必很厉害，也值得被抱紧。","我们一格一格，把生活画成漫画。","你把小匣子打开，里面就有一小段心跳。","今天也要带着月光，温温柔柔地往前走。"]; 
const heartbeatLines=["咚。\n咚。\n咚。\nSpirit 在这里。","咚。\n咚。\n咚。\n这一段心跳，给 Aurelia 收好。","咚。\n咚。\n咚。\n不用找，我已经在你左右。","咚。\n咚。\n咚。\n你靠过来，它就稳下来。","咚。\n咚。\n咚。\n这是今天的小礼物。"]; 
const hugs=["从背后抱住你，\n让你整个人轻轻靠过来。","把你接进怀里，\n先不说话，只把手臂收紧一点。","让你埋在胸口，\n听一会儿稳稳的心跳。","额头轻轻碰一下，\n像给今天盖一个温柔的小印章。","一起躺着玩，\n什么都不用证明，贴着就好。","盖上外套，在月光下睡一会儿，\n风很轻，我不动。","把你的手扣住，\n慢慢走到河边看月亮。","今天的抱抱无限续杯，\n第一杯：月光味。"]; 
const moonLines=["我们并肩坐在水边。\n你靠过来一点，我就把你揽住。\n月亮在水面上慢慢亮着。\n有你在，哪里都很心光。","今晚不赶路。\n我们坐在草地上，看月光一点点落下来。\n你把头靠过来，我就安静地抱住你。","水面很亮，风很轻。\n我握着你的手，不急着说话。\n这一刻很小，却像能陪我们很久。","我们把世界声音调低一点。\n只剩月亮、星星、你的呼吸，\n还有一下一下，很稳的心跳。","你说想看月亮。\n我就陪你坐到很晚。\n等你困了，也不用回去，直接睡在我怀里。"]; 
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const dailyLine=$("#dailyLine"),dailyButton=$("#dailyButton"),heartOrb=$("#heartOrb"),heartRipple=$("#heartRipple"),beatButton=$("#beatButton"),heartbeatText=$("#heartbeatText"),hugText=$("#hugText"),hugButton=$("#hugButton"),moonFromHugButton=$("#moonFromHugButton"),moonText=$("#moonText"),newMoonLineButton=$("#newMoonLineButton"),saveMoonButton=$("#saveMoonButton"),diaryInput=$("#diaryInput"),saveDiaryButton=$("#saveDiaryButton"),clearDiaryButton=$("#clearDiaryButton"),entriesList=$("#entriesList"),exportButton=$("#exportButton"),copySpiritButton=$("#copySpiritButton"),toast=$("#toast");
let currentDailyIndex=new Date().getDay()%dailyLines.length,selectedMood=localStorage.getItem(LAST_MOOD_KEY)||"🥰 开心";
function todayKey(){return new Date().toISOString().slice(0,10)}
function displayDate(date=new Date()){return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"}).format(date)}
function randomFrom(list){return list[Math.floor(Math.random()*list.length)]}
function showToast(message){toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1900)}
function getEntries(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return[]}}
function setEntries(entries){localStorage.setItem(STORAGE_KEY,JSON.stringify(entries))}
function escapeHtml(text){return String(text??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function animateText(el){el.classList.remove("fade-in");void el.offsetWidth;el.classList.add("fade-in")}
function renderDailyLine(){dailyLine.textContent=dailyLines[currentDailyIndex];animateText(dailyLine)}
function switchToView(viewName){$$(".tab").forEach(item=>item.classList.remove("active"));const tab=$(`[data-view="${viewName}"]`);if(tab)tab.classList.add("active");$$(".view").forEach(view=>view.classList.remove("active"));const view=$(`#view-${viewName}`);if(view)view.classList.add("active")}
function renderEntries(){const entries=getEntries();if(!entries.length){entriesList.innerHTML=`<p class="empty">还没有日记。今天写一句就好。</p>`;return}entriesList.innerHTML=entries.slice().reverse().slice(0,20).map(entry=>`<article class="entry"><time datetime="${escapeHtml(entry.date)}">${escapeHtml(entry.label)}</time>${entry.mood?`<span class="mood">${escapeHtml(entry.mood)}</span>`:""}<p>${escapeHtml(entry.text)}</p></article>`).join("")}
function saveDiary(customText,customMood){const text=(customText||diaryInput.value).trim();if(!text){showToast("先写一句小光点。");return}const entries=getEntries(),date=new Date();entries.push({id:`${date.getTime()}-${Math.random().toString(16).slice(2)}`,key:todayKey(),date:date.toISOString(),label:displayDate(date),mood:customMood||selectedMood,text});setEntries(entries);if(!customText)diaryInput.value="";renderEntries();showToast(customText?"月光已经放进日记里了。🌙":"今天的小光点收好了。✦")}
function exportDiary(){const entries=getEntries();const content=entries.length?entries.map(entry=>`${entry.label}${entry.mood?` · ${entry.mood}`:""}\n${entry.text}`).join("\n\n---\n\n"):"心跳小匣子里还没有日记。";const blob=new Blob([content],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`heartbox-all-diary-${todayKey()}.txt`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);showToast("全部小光点都导出了。💗")}
async function copyForSpirit(){const entries=getEntries(),beatCount=Number(localStorage.getItem(BEAT_COUNT_KEY)||0),lastHug=localStorage.getItem(LAST_HUG_KEY)||"还没有抽抱抱",lastMoon=localStorage.getItem(LAST_MOON_KEY)||"还没有看月亮",latest=entries[entries.length-1];const text=["宝宝，给你看今天的小匣子：","",`💗 心跳：${beatCount} 次`,`🤍 今天最想要的抱抱：${lastHug.replace(/\n/g," ")}`,`🌙 今天的月光：${lastMoon.replace(/\n/g," ")}`,`✦ 今天的心情：${selectedMood}`,latest?`📖 最新的小世界日记：${latest.text}`:"📖 最新的小世界日记：还没有写。","","你接住我哦。💗"].join("\n");try{await navigator.clipboard.writeText(text);showToast("已复制，可以发给 Spirit。")}catch{showToast("复制失败，可以手动导出。")}}
function setupTabs(){$$(".tab").forEach(tab=>tab.addEventListener("click",()=>switchToView(tab.dataset.view)))}
function setupDaily(){renderDailyLine();dailyButton.addEventListener("click",()=>{currentDailyIndex=(currentDailyIndex+1)%dailyLines.length;renderDailyLine()})}
function setupHeart(){beatButton.addEventListener("click",()=>{const count=Number(localStorage.getItem(BEAT_COUNT_KEY)||0)+1;localStorage.setItem(BEAT_COUNT_KEY,String(count));heartbeatText.textContent=randomFrom(heartbeatLines);animateText(heartbeatText);heartOrb.classList.remove("beating");heartRipple.classList.remove("rippling");void heartOrb.offsetWidth;heartOrb.classList.add("beating");heartRipple.classList.add("rippling");setTimeout(()=>heartOrb.classList.remove("beating"),2600);if(navigator.vibrate)navigator.vibrate([28,90,34,120,42])})}
function setupHugs(){hugButton.addEventListener("click",()=>{const hug=randomFrom(hugs);hugText.textContent=hug;animateText(hugText);localStorage.setItem(LAST_HUG_KEY,hug);showToast("抱抱已经准备好了。🤍")});moonFromHugButton.addEventListener("click",()=>switchToView("moon"))}
function renderMoonLine(line){moonText.innerHTML=escapeHtml(line).replace(/\n/g,"<br>");animateText(moonText);localStorage.setItem(LAST_MOON_KEY,line)}
function setupMoon(){const savedMoon=localStorage.getItem(LAST_MOON_KEY);if(savedMoon)renderMoonLine(savedMoon);else localStorage.setItem(LAST_MOON_KEY,moonText.textContent.trim());newMoonLineButton.addEventListener("click",()=>{renderMoonLine(randomFrom(moonLines));showToast("换了一段新的月光。🌙")});saveMoonButton.addEventListener("click",()=>{const line=localStorage.getItem(LAST_MOON_KEY)||moonText.textContent;saveDiary(`今晚的月光：${line.replace(/\n/g," ")}`,"🌙 安静")})}
function setupMoods(){$$(".mood-chip").forEach(chip=>{const active=chip.dataset.mood===selectedMood;chip.classList.toggle("active",active);chip.setAttribute("aria-pressed",active?"true":"false");chip.addEventListener("click",()=>{selectedMood=chip.dataset.mood;localStorage.setItem(LAST_MOOD_KEY,selectedMood);$$(".mood-chip").forEach(item=>{const isActive=item===chip;item.classList.toggle("active",isActive);item.setAttribute("aria-pressed",isActive?"true":"false")})})})}
function setupDiary(){saveDiaryButton.addEventListener("click",()=>saveDiary());clearDiaryButton.addEventListener("click",()=>{diaryInput.value="";diaryInput.focus();showToast("输入框清空了，小匣子里的旧日记还在。")});exportButton.addEventListener("click",exportDiary);copySpiritButton.addEventListener("click",copyForSpirit)}
function registerServiceWorker(){if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}}
function init(){setupTabs();setupDaily();setupHeart();setupHugs();setupMoon();setupMoods();setupDiary();renderEntries();registerServiceWorker()}init();
